services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: counter_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@db:5432/counter_db

volumes:
  pg_data:
